---
output: 
  md_document:
    variant: markdown_github
---

## Trabajo individual para la asignatura "Big Data"

<!-- El párrafo de abajo has de dejarlo tal cual. NO HAS DE CAMBIAR NADA!!-->


Repo utilizado para elaborar el trabajo para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2021-2022. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-21-22-web/>.


<!-- En la linea de abajo TIENES QUE SUSTITUIR "perezp44" por tu usuario de Github-->
La versión final del trabajo puede visualizarse en: <https://joorge0603.github.io/trabajo_BigData/>. 


<!-- Abajo podéis escribir lo que queráis, igual un resumen del trabajo, o ..., o ... pero al menos, creo que tienes que poner el título del trabajo y posiblemente tu nombre. Algo que explique porque está el repo en Github-->

El título del trabajo es **¿QUIÉN ES EL GOAT DEL TENIS?**. El autor es Jorge González Andrés. 

Uno de los debates más candentes en los últimos años entre los fanáticos del tenis es sobre quién es el mejor jugador de todos los tiempos. Los candidatos a este título honorífico parecen claros. Roger Federer, Rafael Nadal y Novak Djokovic han roto todos los récords creados y pocos se atreven a dar un nombre distinto al de estos tres tenistas. 

A lo largo de este documento, se establecen una serie de criterios que tratan de dotar a este debate de argumentos objetivos para dar una respuesta a **¿QUIÉN ES EL GOAT DEL TENIS?**. Todas las conclusiones alcanzadas se encuentran respaldadas por datos históricos. De esta forma, este trabajo es una buena fuente para aquellos que deseen conocer la inmensidad de los logros de estos tenistas y, así, formar su propia opinión.


<!-- Finalmente, ACÚERDATE de que cuando hayas hecho los cambios y hayas dejado este archivo como te guste más, TIENES que knittearlo para que los cambios se actualicen en el fichero Readme.md, que es el que finalmente se visualizará en Github. El fichero Readme.md no has de editarlo a mano, sale de knittear Readme.Rmd-->

